### ISSUE TITLE
Can`t install this module.

### ISSUE THREAD

**Issue by Yoda49** [entercritical/dht-sensor#4]
> node-gyp rebuild

make: Entering directory '/home/pi/smarthome/node_modules/dht-sensor/build'
  CXX(target) Release/obj.target/dht-sensor/dht_sensor.o
  CC(target) Release/obj.target/dht-sensor/common_dht_read.o
## **make: cc: Command not found**

dht-sensor.target.mk:89: recipe for target 'Release/obj.target/dht-sensor/common_dht_read.o' failed
make: **\* [Release/obj.target/dht-sensor/common_dht_read.o] Error 127
make: Leaving directory '/home/pi/smarthome/node_modules/dht-sensor/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/smarthome/node_modules/dht-sensor
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Linux 4.1.7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "dht-sensor" "--save"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! dht-sensor@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dht-sensor@0.0.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the dht-sensor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls dht-sensor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/smarthome/npm-debug.log

**Comment by PMudra** [comment]
I believe there is no c/c++ compiler installed on your machine.
Maybe this helps:
`sudo apt-get install build-essential`
