### ISSUE TITLE
reads 0 for AM2302 sensor

### ISSUE THREAD

**Issue by seanpaulkelley** [entercritical/dht-sensor#5]
I have an am2302 sensor.  I know wiring is correct because it works with adafruit python library:

    sensor = Adafruit_DHT.AM2302 #DHT11/DHT22/AM2302  
    pin = 4  

using dht-sensor module with node v 8.9.1 I use pin of 4 and sensor of 22

    var dht = require('dht-sensor');
    var current = dht.read(22, 4);

    console.log(current.humidity); // => 0
    console.log(current.temperature); //=> 0

Any ideas on what my be the problem?

**Comment by entercritical** [comment]
Please update version 0.0.5.
@PMudra updated error but I forgot publishing.
Thanks you.
